export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SIGNOUT = 'SIGNOUT';

export const GET_EMPLOYEE_PROFILES = 'GET_EMPLOYEE_PROFILES';
export const GET_EMPLOYEE_PROFILES_ERROR = 'GET_EMPLOYEE_PROFILES_ERROR';

export const GET_EMPLOYEE_PROFILE = 'GET_EMPLOYEE_PROFILE';
export const GET_EMPLOYEE_PROFILE_ERROR = 'GET_EMPLOYEE_PROFILE_ERROR';

export const CREATE_EMPLOYEE_PROFILE = 'CREATE_EMPLOYEE_PROFILE';
export const CREATE_EMPLOYEE_PROFILE_ERROR = 'CREATE_EMPLOYEE_PROFILE_ERROR';

export const UPDATE_EMPLOYEE_PROFILE = 'UPDATE_EMPLOYEE_PROFILE';
export const UPDATE_EMPLOYEE_PROFILE_ERROR = 'UPDATE_EMPLOYEE_PROFILE_ERROR';

export const DELETE_EMPLOYEE_PROFILE = 'DELETE_EMPLOYEE_PROFILE';
export const DELETE_EMPLOYEE_PROFILE_ERROR = 'DELETE_EMPLOYEE_PROFILE_ERROR';